name: TapuinoCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch, and now hopefully for tags
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
    # Make the local_config.h file!
      - name: Add config-user.h
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./include/config-user.h
          contents: "#pragma once\n#define I2C_DISP_ADDR 0x27\n#define I2C_DISP_TYPE I2C_DISP_TYPE_HD44780"
          write-mode: overwrite 
          
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@0.1.0
        with:
          jobs: 6
          silent: false
          verbose: true
          disable-auto-clean: false

      - name: Get notes
        id: generate_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: anmarkoulis/commitizen-changelog-reader@master
        with:
          tag_name: ${{ github.ref }}
          changelog: ./RELEASE_NOTES.md

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ format('{0} {1}', '[**Release Notes:**](https://github.com/sweetlilmre/TapuinoNext/blob/main/RELEASE_NOTES.md)', join(fromJson(steps.generate_notes.outputs.notes).notes, '')) }}
          files: .pio/build/esp32dev/update.bin
